name: patrol_integ
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  flutter_timezone: ^1.0.8
  geolocator: ^10.1.0
  permission_handler: ^10.4.5
  timezone: ^0.9.2
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^7.0.0+1
  patrol: ^3.7.2
  patrol_finders: 2.1.2

flutter:
  uses-material-design: true



          
patrol:
  app_name: patrol_integ
  android:
    package_name: com.example.patrol_integ
  ios:
    bundle_id: com.example.patrolInteg
