name: patrol_integ
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  patrol: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  patrol_finders: ^2.0.2

flutter:
  uses-material-design: true


patrol:
  patrol:
  app_name: My App
  android:
    package_name: com.example.patrol_integ
  ios:
    bundle_id: com.example.patrolInteg