name: patrol_integ
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
    animations: ^2.0.8
  confetti: ^0.7.0
  dispose_scope: ^2.1.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_holo_date_picker: ^1.1.3
  flutter_local_notifications: ^16.1.0
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_sign_in: ^6.1.6
  http: ^1.1.0
  permission_handler: ^11.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  leancode_lint: ^12.1.0
  flutter_lints: ^3.0.0
  patrol: ^3.7.2
  patrol_finders: 2.1.2

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/app_icon.png'

flutter_native_splash:
  color: '#1F1F1F'
  image: 'assets/icon/splash_icon.png'
  android_12:
    image: 'assets/icon/splash_icon.png'
    color: '#1F1F1F'

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
          
patrol:
  app_name: patrol_integ
  android:
    package_name: com.example.patrol_integ
  ios:
    bundle_id: com.example.patrolInteg
